//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.StagesMSMQRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StagesMSMQRef.IStagesMSMQ")]
    public interface IStagesMSMQ {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStagesMSMQ/AddStage")]
        void AddStage(BLL.DTO.StageDto stage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IStagesMSMQ/AddStage")]
        System.Threading.Tasks.Task AddStageAsync(BLL.DTO.StageDto stage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStagesMSMQChannel : Client.StagesMSMQRef.IStagesMSMQ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StagesMSMQClient : System.ServiceModel.ClientBase<Client.StagesMSMQRef.IStagesMSMQ>, Client.StagesMSMQRef.IStagesMSMQ {
        
        public StagesMSMQClient() {
        }
        
        public StagesMSMQClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StagesMSMQClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StagesMSMQClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StagesMSMQClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddStage(BLL.DTO.StageDto stage) {
            base.Channel.AddStage(stage);
        }
        
        public System.Threading.Tasks.Task AddStageAsync(BLL.DTO.StageDto stage) {
            return base.Channel.AddStageAsync(stage);
        }
    }
}
